spring.application.name=un

server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://mysql:3306/ufanetProj
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always

# ActiveMQ
spring.activemq.broker-url=tcp://activemq:61616?wireFormat.maxFrameSize=104857600
spring.activemq.user=admin
spring.activemq.password=admin
spring.activemq.pool.enabled=false

# Actuator + Prometheus
management.endpoints.web.exposure.include=health,prometheus
management.metrics.export.prometheus.enabled=true

management.metrics.distribution.percentiles-histogram.http.server.requests=true

management.metrics.tags.application=balance-system